name: GPS
main: com.vistamaresoft.gps.Gps
version: 1.4.0
author: Maurizio M. Gavioli aka Miwarre
team: VistaMare Software
description: "To aid the player in world navigation and positioning.
Allows to set a home point and up to 15 waypoints; displays current
player position and optionally distance and radial to home/waypoint."
license: Creative Common by-sa
website: http://www.vistamaresoft.com
